steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/vllm-images/labeling:latest'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/vllm-images/labeling:latest'

options:
  machineType: 'E2_HIGHCPU_32'  # build mais rápido
  diskSizeGb: 100
timeout: '3600s'
